name: GenerateSnake

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  update-repository:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            img/snake.svg
            img/snake-dark.svg?palette=github-dark
          color_snake: '#FF7F50'
          color_dots: '#C0C0C0,#94b4c5,#6c9ac4,#527fb4,#3b6aa3'

      - name: Commit & Push SVG
        uses: EndBug/add-and-commit@v9
        with:
          add: 'img/*.svg'
          message: ':rocket: Update GitHub Snake'
          default_author: github_actions
          branch: main
